server:
  port: 8084
  shutdown: graceful
spring:
  application:
    name: sentinel
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
management:
  endpoints:
    web:
      exposure:
        include: "*"